/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.student.assignment4;

import java.io.FileNotFoundException;
import java.io.FileReader;

/**
 *
 * @author s0542191
 */
public class AssignmentForm4 extends javax.swing.JFrame {

    private String inputFileName = "";
    private String outputFileName = "";
    private int numberOfField = 0;
    private int numberOfPrecision = 0;
    private int numberOfColumns = 0;

    /**
     * Creates new form assignmentForm4
     */
    public AssignmentForm4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldInputFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldOutputFile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonProcess = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelNumberOfField = new javax.swing.JLabel();
        jTextFieldNumberField = new javax.swing.JTextField();
        jLabelNumberOfPrecision = new javax.swing.JLabel();
        jTextFieldNumberOfPrecision = new javax.swing.JTextField();
        jLabelNumberOfColumns = new javax.swing.JLabel();
        jTextFieldNumberOfColumns = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextFieldInputFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldInputFile.setText("random.txt");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Input File");

        jTextFieldOutputFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldOutputFile.setText("output.txt");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Output File");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Settings:");

        jButtonProcess.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonProcess.setText("Process");
        jButtonProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcessActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 0, 6));

        jLabelNumberOfField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNumberOfField.setText("Number of Field width");
        jPanel1.add(jLabelNumberOfField);

        jTextFieldNumberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNumberField.setText("2");
        jPanel1.add(jTextFieldNumberField);

        jLabelNumberOfPrecision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNumberOfPrecision.setText("Number of Precision");
        jPanel1.add(jLabelNumberOfPrecision);

        jTextFieldNumberOfPrecision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNumberOfPrecision.setText("2");
        jPanel1.add(jTextFieldNumberOfPrecision);

        jLabelNumberOfColumns.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNumberOfColumns.setText("Number of Columns (1-5)");
        jPanel1.add(jLabelNumberOfColumns);

        jTextFieldNumberOfColumns.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNumberOfColumns.setText("3");
        jPanel1.add(jTextFieldNumberOfColumns);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonProcess)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldInputFile))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldOutputFile))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonProcess)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcessActionPerformed
        getUserInput();
    }//GEN-LAST:event_jButtonProcessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentForm4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNumberOfColumns;
    private javax.swing.JLabel jLabelNumberOfField;
    private javax.swing.JLabel jLabelNumberOfPrecision;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldInputFile;
    private javax.swing.JTextField jTextFieldNumberField;
    private javax.swing.JTextField jTextFieldNumberOfColumns;
    private javax.swing.JTextField jTextFieldNumberOfPrecision;
    private javax.swing.JTextField jTextFieldOutputFile;
    // End of variables declaration//GEN-END:variables

    private void checkUserInput() {
        // check field value
        checkFieldValue();
        // check precision value
        checkPrecisionValue();
        // check number of columns value
        checkNumberOfColumns();
    }

    private void checkFieldValue() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void checkPrecisionValue() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void checkNumberOfColumns() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void getUserInput() {
        checkInputFile();
        createOuputFile();
        checkUserInput();
    }

    private void checkInputFile() {
        inputFileName = jTextFieldInputFile.getText();
        try{
            FileReader inputFile = new FileReader(inputFileName);
        }
        catch(FileNotFoundException fileError){
            System.out.println("File not found");
        }
    }

    private void createOuputFile() {
        outputFileName = jTextFieldOutputFile.getText();
        try{
            FileReader outputFile = new FileReader(outputFileName);
        }
        catch(FileNotFoundException fileError){
            System.out.println("File not found");
        }
    
    }
    
}
