/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.student.game1;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author s0542191
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    // shape 0 - is circle
    // shape 1 - is x
    private int shape = 0;
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 550));
        setSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        jButton11.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton11.setToolTipText("");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton11);

        jButton12.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton12);

        jButton13.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton13);

        jButton21.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton21);

        jButton22.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton22);

        jButton23.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton23);

        jButton31.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton31);

        jButton32.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton32);

        jButton33.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClicked(evt);
            }
        });
        jPanel1.add(jButton33);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 400, 400));
        jPanel1.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Its O turn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 20));

        jLabel2.setText("O win count: 0");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel3.setText("X win count: 0");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClicked
        JButton theButton = (JButton)evt.getSource();
        if (theButton.getText().equals("")){
            theButton.setText((shape==1)? "X": "O");
        shape = (shape == 1)? 0:1;
        String nextLetter = (shape == 0)? "O":"X";
        jLabel1.setText("Its " + nextLetter + " turn");
        checkWinner();
        }
        
    }//GEN-LAST:event_jButtonClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void checkWinner() {
        String winnerPattern = "";
        
        // row 1
        winnerPattern += jButton11.getText();
        winnerPattern += jButton12.getText();
        winnerPattern += jButton13.getText();
        winnerPattern += " ";
        
        // row 2
        winnerPattern += jButton21.getText();
        winnerPattern += jButton22.getText();
        winnerPattern += jButton23.getText();
        winnerPattern += " ";
        
        // row 3
        winnerPattern += jButton31.getText();
        winnerPattern += jButton32.getText();
        winnerPattern += jButton33.getText();
        winnerPattern += " ";
        
        // col 1
        winnerPattern += jButton11.getText();
        winnerPattern += jButton21.getText();
        winnerPattern += jButton31.getText();
        winnerPattern += " ";
        
        // col 2
        winnerPattern += jButton12.getText();
        winnerPattern += jButton22.getText();
        winnerPattern += jButton32.getText();
        winnerPattern += " ";
        
        // col 3
        winnerPattern += jButton11.getText();
        winnerPattern += jButton22.getText();
        winnerPattern += jButton33.getText();
        winnerPattern += " ";
        
        // diag 1
        winnerPattern += jButton11.getText();
        winnerPattern += jButton22.getText();
        winnerPattern += jButton33.getText();
        winnerPattern += " ";
        
        // diag 2
        winnerPattern += jButton13.getText();
        winnerPattern += jButton22.getText();
        winnerPattern += jButton31.getText();
        winnerPattern += " ";
        
        // Display the winner
        if (winnerPattern.contains("XXX") || winnerPattern.contains("OOO")){
            String letterWinner;
            if (winnerPattern.contains("XXX")){
                letterWinner = "X";
            }else{
                letterWinner = "O";
            }
            JOptionPane.showMessageDialog(this, "We have a winner. Letter " + letterWinner);
            clearBoard();
        }
    }

    private void clearBoard() {
        jButton11.setText("");
        jButton12.setText("");
        jButton13.setText("");
        jButton21.setText("");
        jButton22.setText("");
        jButton23.setText("");
        jButton31.setText("");
        jButton32.setText("");
        jButton33.setText("");
    }
}
